<?php require('header.phtml') ?>
<h3>Create Product</h3>
<form method="post" type="multipart/form-data" action="/create">
    <p>
        Name: <input type="text" name="name">
    </p>
    <p>
        Price: <input type="text" name="price">
    </p>
    <p>
        Description: <input type="text" name="description">
    </p>
    <!--
        todo: Add picture upload as a new feature after basic CRUD is working
    -->
    <input type="submit">
</form>
<?php require('footer.phtml') ?>