<?php require('header.phtml') ?>
<h3>Create Product</h3>
<form method="post" type="multipart/form-data" action="/edit">
    <input type="hidden" name="id" value="<?php echo $data['product']->getId() ?>">
    <p>
        Name: <input type="text" name="name" value="<?php echo $data['product']->getName() ?>">
    </p>
    <p>
        Price: <input type="text" name="price" value="<?php echo $data['product']->getPrice() ?>">
    </p>
    <p>
        Description: <input type="text" name="description" value="<?php echo $data['product']->getDescription() ?>">
    </p>
    <!--
        todo: Add picture upload as a new feature after basic CRUD is working
    -->
    <input type="submit">
</form>
<?php require('footer.phtml') ?>