<?php require('header.phtml') ?>
<h3>Product Listing Page</h3>

<h4>Main Menu</h4>
<ul>
    <li><a href="/create">Create a product</a></li>
</ul>

<?php if ( $data['count'] > 10): ?>
    Pages:
    <?php $page = 0 ?>
    <?php for($i = 1; $i < $data['count']; $i = $i + 10): ?>
        <?php $page = $page + 1 ?>
        <a href="/skip/<?php echo $i ?>"><?php echo $page ?></a>
    <?php endfor ?>
<?php endif ?>


<table>
    <th>Products</th>
    <tr>
        <td>Picture</td>
        <td><a href="/name">Name</a></td>
        <td><a href="/price">Price</a></td>
        <td>Description</td>
        <td>Actions</td>
    </tr>
    <?php foreach ($data['products'] as $product): ?>
        <tr>
            <td><a href="/details/<?php echo $product->getId() ?>"><img src="/uploads/<?php echo $product->getPicture() ?>" alt="product picture"></a></td>
            <td><a href="/details/<?php echo $product->getId() ?>"><?php echo $product->getName() ?></a></td>
            <td><?php echo $product->getPrice() ?></td>
            <td><?php echo $product->getDescription() ?></td>
            <td>
                <a href="/edit/<?php echo $product->getId() ?>">Edit</a>&nbsp;
                <a href="/confirm-delete/<?php echo $product->getId() ?>">Delete</a>&nbsp;
            </td>
        </tr>
    <?php endforeach ?>
</table>

<?php require('footer.phtml') ?>